/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const /: typeof import('from')['/']
  const Component: typeof import('vue')['Component']
  const ComponentPublicInstance: typeof import('vue')['ComponentPublicInstance']
  const ComputedRef: typeof import('vue')['ComputedRef']
  const ExtractDefaultPropTypes: typeof import('vue')['ExtractDefaultPropTypes']
  const ExtractPropTypes: typeof import('vue')['ExtractPropTypes']
  const ExtractPublicPropTypes: typeof import('vue')['ExtractPublicPropTypes']
  const InjectionKey: typeof import('vue')['InjectionKey']
  const PropType: typeof import('vue')['PropType']
  const Ref: typeof import('vue')['Ref']
  const VNode: typeof import('vue')['VNode']
  const WritableComputedRef: typeof import('vue')['WritableComputedRef']
  const e: typeof import('from')['e']
  const onKeyStroke: typeof import('@vueuse/core')['onKeyStroke']
  const r: typeof import('from')['r']
  const u: typeof import('from')['u']
  const v: typeof import('from')['v']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { useForm, Head, Link } from '@inertiajs/vue3'
  import('@inertiajs/vue3')
}
